name: GitHub Actions Issue Example
on:
  issues:
    types: opened
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      run: gh issue view $ISSUE_NUMBER --json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
