name: GitHub Actions Issue Example
on:
  issues:
    types: opened
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ISSUE_NUMBER: ${{ github.event.issue.number }}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Close Issue
      run: gh issue close $ISSUE_NUMBER
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Show Issue
      run: gh issue view $ISSUE_NUMBER --json title,body
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

