name: GitHub Actions Issue Example
on:
  issues:
    types: opened
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
